data-directory: "data"
paired-end: False # Important to specify this correctly!
genome: "mm10" # Important to specify this correctly!
trimmomatic-trimmer: "SLIDINGWINDOW:51:20"
fastqc-args:
  --threads: "6"
trimmomatic-args:
  -threads: "6"
hisat2-args:
  --no-spliced-alignment: "" # Important for ChIPseq! Can remove if RNAseq.
  -p: "6"
  --very-sensitive: ""
  -k: "1"
samtools-sort-args:
  -@: "6"
samtools-markdup-args:
  -@: "6"
samtools-index-args:
  -@: "6"
bamCoverage-args:
  --effectiveGenomeSize: "2652783500" # Ensure this aligns with your genome!
  -p: "6"
  --normalizeUsing: "RPKM"
  -e: "300"
computeMatrix-args:
  --referencePoint: "TSS"
  -a: "3000"
  -b: "3000"
  -p: "6"
plotHeatmap-args:
  --colorMap: "Blues"
macs3-callpeak-args:
  -g: "mm" # Ensure this aligns with your genome!
  -q: "0.0001"
  --nomodel: ""
  --extsize: "300"
findMotifsGenome-args:
  -size: "200" # Note that deleting this will cause HOMER to fail!
