# CONFIG.YML
# Last updated 03/24/24 by Peter Lais of the DeMayo lab
#
# This file defines the configuration options of the pipeline. The specific
# tasks that the pipeline performs will depend on the options you select
# here. Please read through each of the below options and change them as you
# need; just be sure that you set each of them to the correct values for
# your projects. Example config files are also located in the "examples"
# folder.
#
# "Main configuration options" are options that are central to the pipeline
# itself and the Python backend underlying the pipeline.
#
# "Command-line program arguments" individually control the programs that form
# the RNAseq and ChIPseq processing pipelines. Some arguments may be
# repetitive, but this is the consequence of using many separate command-line
# programs. Each of the command-line programs have their own documentation
# to help people understand what options are available. Generally, calling
# "[programname] -h/-help/--help" should show you the available options.
# The command needed to display help information is written above each block.

# Main configuration options
data-directory: "data"
paired-end: False                          # Are your FASTQ files paired-end?
genome: "mm10"                             # UCSC (or other) base genome to analyze against
allow-prebuilt-genome: True                # Don't force-rebuild genome if already built
mark-duplicate-reads: False                # Use SAMTools to mark duplicate reads
trimmomatic-trimmer: "SLIDINGWINDOW:51:20" # See trimmomatic docs (below)
overall-comparisons: True                  # Perform overall comparisons (ChIP)
pairwise-comparisons: True                 # Perform differential peak calling (ChIP)
joblib-threads: 6                          # Threads to allocate to joblib

# genome can be any of the following options:
# genome with UCSC entry
# genome with custom fasta, naming (optional), and gtf
# 
# homer genome can be any of the following options:
# unset (defaults to genome options)
# a single string (installed homer genome)
# a fasta, naming gtf

# Command-line program arguments
fastqc-args:                               # "fastqc -h" for help
  --threads: 6
multiqc-args:                              # "multiqc -h" for help
trimmomatic-args:                          # "trimmomatic -h" for help
  -threads: 6
hisat2-args:                               # "hisat2 -h" for help
  --no-spliced-alignment: ""               # Important for ChIPseq! Can remove if RNAseq.
  -p: 6
  --very-sensitive: ""
  -k: 1
hisat2-build-args:                         # "hisat2-build -h" for help
  -p: 6
samtools-sort-args:                        # "samtools sort" for help
  -@: 6
samtools-fixmate-args:                     # "samtools fixmate" for help
samtools-markdup-args:                     # "samtools markdup" for help
  -@: 6
samtools-index-args:                       # "samtools index" for help
  -@: 6
featureCounts-args:                        # "featureCounts" for help
bamCoverage-args:                          # "bamCoverage -h" for help
  --effectiveGenomeSize: 2652783500        # Ensure this aligns with your genome! See above help.
  -p: 6
  --normalizeUsing: "RPKM"
  # --samFlagInclude: 64                   # Ensure this is set (remove first #) for paired-end RNAseq data!
  -e: 300
computeMatrix-reference-point-args:        # "computeMatrix reference-point -h" for help
  --referencePoint: "TSS"
  -a: 3000
  -b: 3000
  -p: 6
plotHeatmap-args:                          # "plotHeatmap -h" for help
  --colorMap: "Blues"
macs3-callpeak-args:                       # "macs3 callpeak -h" for help
  -g: "mm"                                 # Ensure this aligns with your genome! See above help.
  -q: 0.0001
  --nomodel: ""
  --extsize: 300
macs3-bdgdiff-args:                        # "macs3 bdgdiff -h" for help
bedtools-intersect-args:                   # "bedtools intersect -h" for help
findMotifsGenome-args:                     # "findMotifsGenome.pl" for help
  -size: 200                               # Note that deleting this will cause HOMER to fail!
annotatePeaks-args:                        # "annotatePeaks.pl" for help
  -cpu: 6
